title: <p align="center"> Mahalakshmi T </p>
logo: /assets/img/MJ.jpg

description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahalakshmi-totad/">LinkedIn</a> |
  <a href="https://github.com/Mahalakshmi-Totad">GitHub</a>

 <br>   
  I'm working as Senior Engineer.
  My day to day techlogies involve ReactJS, Kotlin, Micronaut. 
  I'm aspiring to work with Generative AI & Machine learning related problems.
  <br>
  </p>


theme: jekyll-theme-minimal
